# [로컬 서버 설정]
server.port=8080

# [DB 설정] 로컬 대신 AWS 서버 DB 주소를 넣습니다.
spring.datasource.url=jdbc:mariadb://110.165.19.54:3306/board_db
spring.datasource.username=board
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
server.servlet.session.persistent=false