# [로컬 서버 설정]
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/board_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

server.servlet.session.persistent=false

# 이미지 업로드 경로 설정
app.upload.board-image-dir=C:/workspace/uploads/board-images

# 업로드 용량 설정
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB