# \uC11C\uBC84 \uC124\uC815
server.port=80
server.address=0.0.0.0
\uFFFD
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/board_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver